import countries from "../../../Store/Slices/TemplateHelpers/Counties";

const CreateTemplatesRacks = {
  "# Operation *": { value: "ADD" },
  "Object *": { value: "MODEL" },
  "Status *": { value: "PLANNED" },
  "!!!OpenRUArray": {
    value: [],
  },
  "Make *": {
    type: "text",
    value: "",
    placeholder: "Enter Make (e.g., Brand, Manufacturer)",
    options: [],
    required: false,
    APIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "Model Name *": {
    type: "text",
    value: "",
    placeholder: "Enter Model Name",
    options: [],
    required: false,
    APIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "New Model Name": {
    type: "text",
    value: "",
    placeholder: "Enter New Model Name",
    options: [],
    required: false,
    APIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "Part Number": {
    type: "text",
    value: "",
    placeholder: "Enter Part Number",
    options: [],
    required: false,
    APIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "New Part Number": {
    type: "text",
    value: "",
    placeholder: "Enter New Part Number",
    options: [],
    required: false,
    APIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "Rack Units *": {
    type: "number",
    value: 1,
    placeholder: "Input Here",
    options: [],
    required: false,
    APIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  Description: {
    type: "textarea",
    value: "",
    placeholder: "Enter Description",
    options: [],
    required: false,
    aPIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "Made in": {
    type: "select",
    value: "",
    options: countries,
    required: false,
    aPIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "Weight Capacity": {
    type: "number",
    value: 0,
    placeholder: "Enter Weight Capacity (in lbs)",
    options: [],
    required: false,
    aPIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "Class *": {
    type: "text",
    value: "Cabinet",
    options: [],
    required: false,
    disabled: true,
    aPIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "Subclass**": {
    type: "text",
    value: "N/A",
    options: [],
    required: false,
    disabled: true,
    aPIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "Mounting *": {
    type: "select",
    value: "",
    options: ["Select", "Free-Standing", "Suspended"],
    required: false,
    aPIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "Form Factor *": {
    type: "select",
    value: "",
    options: ["Select", "2-Post Frame", "4-Post Enclosure"],
    required: false,
    aPIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "Height *": {
    type: "number",
    value: 0,
    placeholder: "Enter Height (in inches)",
    options: [],
    required: false,
    aPIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  Width: {
    type: "number",
    value: 0,
    placeholder: "Enter Width (in inches)",
    options: [],
    required: false,
    aPIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  Depth: {
    type: "number",
    value: 0,
    placeholder: "Enter Depth (in inches)",
    options: [],
    required: false,
    aPIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  Weight: {
    type: "number",
    value: 0,
    placeholder: "Enter Weight (in lbs)",
    options: [],
    required: false,
    aPIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  Units: {
    type: "number",
    value: 0,
    placeholder: "Enter Units",
    options: [],
    required: false,
    aPIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  Ports: {
    type: "number",
    value: 0,
    placeholder: "Input Here",
    options: [],
    required: false,
    disabled: false,
    APIMatch: "DataPortsCount",
    NEXT: "HOLD FOR ADDITIONAL INFO",
    Export: "",
  },
  Notes: {
    type: "textarea",
    value: "",
    placeholder: "Enter Notes",
    options: [],
    required: false,
    aPIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
};

export default CreateTemplatesRacks;
