export const Template = {
  Make: "",
  Model: "",
  "New Model Name": "",
  "Part Number": "",
  "New Part Number": "",
  Description: "",
  "Made in": "",
  "Warranty Period": "",
  Class: "",
  SubClass: "",
  Mounting: "",
  "Form Factor": "",
  Height: "",
  Width: "",
  Depth: "",
  Weight: "",
  Units: "",
  Status: "",
  URL: "",
  RUHeight: "",
  DataPortsCount: 0,
  PowerPortsCount: 0,
  FrontSlotsCount: 0,
  BackSlotsCount: 0,
  Notes: "",
};

export const TemplateKeyRequired = {
  Make: true,
  Model: true,
  "New Model Name": false,
  "Part Number": false,
  "New Part Number": false,
  Description: false,
  "Made in": false,
  "Warranty Period": false,
  Class: true,
  SubClass: true,
  Mounting: true,
  "Form Factor": false,
  Height: false,
  Width: false,
  Depth: false,
  Weight: false,
  Units: false,
  Status: false,
  URL: false,
  RUHeight: false,
  DataPortsCount: true,
  PowerPortsCount: true,
  FrontSlotsCount: true,
  BackSlotsCount: true,
  Notes: false,
};

export const TemplateKeyTypes = {
  Make: "text",
  Model: "text",
  "New Model Name": "text",
  "Part Number": "text",
  "New Part Number": "text",
  Description: "textarea",
  "Made in": "text",
  "Warranty Period": "text",
  Class: "select",
  SubClass: "select",
  Mounting: "select",
  "Form Factor": "text",
  Height: "scale",
  Width: "scale",
  Depth: "scale",
  Weight: "scale",
  Units: "number",
  Status: "text",
  URL: "text",
  Notes: "textarea",
  RUHeight: "number",
  DataPortsCount: "number",
  PowerPortsCount: "number",
  FrontSlotsCount: "number",
};

export const TemplateOptions = {
  Class: [
    "AC Distribution",
    "Battery",
    "Cabinet",
    "Data Panel",
    "DC Distribution",
    "DC Power System",
    "Device",
    "Floor PDU",
    "HVAC",
    "Network",
    "Passive",
    "Power Outlet",
    "Power Source",
    "Probe",
    "Rack PDU",
    "UPS",
  ],
  SubClass: [
    "AC Bay",
    "Load Device",
    "Other Device",
    "Power Panel",
    "Switch",
    "Transformer",
    "UPS Bank",
    "Container",
    "DC Bay",
    "DC Panel",
    "Plant",
    "Plant Bay",
    "Plant Panel",
    "Rectifier",
    "Blade Chassis",
    "Blade Server",
    "Standard",
    "Virtual Machine",
    "Busway",
    "Local",
    "Remote",
    "Cooling Unit",
    "Cooling Zone",
    "Heat Rejection",
    "Blade",
    "Chassis",
    "NetworkStack",
    "Blanking Plate",
    "Shelf",
    "Busway Outlet",
    "Whip Outlet",
    "Fuel Tank",
    "Generator",
    "Utility Feed",
    "AC Power",
    "DC FAP",
    "Rack Inverter",
  ],
  Mounting: ["Busway", "VStack", "Blade", "Rackable", "ZeroU", "Free-Standing", "Non-Rackable", "Suspended"],
};
