const AssetsAdditionalFields = {
  hardwareHeadingGroup: {
    "Part Number": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Serial Number": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Asset Tag": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "eAsset Tag": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
  },
  identityHeadingGroup: {
    "New Name": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    Alias: {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    Type: {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    Function: {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    Customer: {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
  },
  statusHeadingGroup: {
    "Planned Decomm. Date": {
      type: "date",
      value: "2007-06-09",
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Is Archived": {
      type: "bool",
      value: false,
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
  },
  placementHeadingGroup: {
    "New Location": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Location Reference": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Planning Date": {
      type: "date",
      value: "2007-06-09",
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
  },
  assetAndMaintenanceHeadingGroup: {
    Contact: {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Contact Team": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Project Number": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "PO Number": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Purchase Price": {
      type: "number",
      value: 0,
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Purchase Date": {
      type: "date",
      value: "2007-06-09",
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Installation Date": {
      type: "date",
      value: "2007-06-09",
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "SLA Profile": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Contract Number": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Contract Amount": {
      type: "number",
      value: 0,
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Contract Start Date": {
      type: "date",
      value: "2007-06-09",
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Contract End Date": {
      type: "date",
      value: "2007-06-09",
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Created On": {
      type: "date",
      value: "2007-06-09",
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Last Updated On": {
      type: "date",
      value: "2007-06-09",
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Created By": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Last Updated By": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    Notes: {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
  },
  configurationHeadingGroup: {
    "Operating System": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    Domain: {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "CPU Type": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "CPU Quantity": {
      type: "number",
      value: 0,
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "RAM (GB)": {
      type: "number",
      value: 0,
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Disk (GB)": {
      type: "number",
      value: 0,
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    Users: {
      type: "number",
      value: 0,
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    Processes: {
      type: "number",
      value: 0,
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    Services: {
      type: "number",
      value: 0,
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "VM Manager": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "VM Cluster": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "is VM Host": {
      type: "bool",
      value: false,
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
  },
};

export default AssetsAdditionalFields;
