const Ceiling = [
  "Select",
  "Suspended Ceiling Tiles (Acoustic Ceiling Tiles)",
  "Exposed Grid Ceiling",
  "Drop Ceiling",
  "Open Ceiling (Industrial Look)",
  "Gypsum Board Ceiling",
  "Metal Ceiling Panels",
  "T-Bar Ceiling",
  "Plaster Ceiling",
  "Wooden Ceiling Panels",
  "Exposed Ductwork Ceiling",
  "Fiberglass Ceiling Tiles",
  "Aluminum Ceiling Panels",
  "Mineral Fiber Ceiling Tiles",
  "Glass Ceiling",
  "Coffered Ceiling",
  "Vaulted Ceiling",
  "Wooden Beams Ceiling",
  "Decorative Ceiling Tiles",
  "Perforated Ceiling Panels",
  "Cloud Ceiling (Floating Panels)",
  "Stretch Ceiling",
  "Fabric Ceiling Panels",
  "Metal Mesh Ceiling",
  "Styrofoam Ceiling Tiles",
  "Painted Concrete Ceiling",
  "Polystyrene Ceiling Tiles",
  "Bamboo Ceiling",
  "Copper Ceiling Panels",
  "Mirror Ceiling",
  "Custom Ceiling Design",
  // Add more types as needed
];

const Floor = [
  "Select",
  "Raised Access Floor (RAF)",
  "Concrete Slab Floor",
  "Grated Tiles",
  "Cementitious Infill Panels",
  "Vinyl Composite Tile (VCT)",
  "Carpet",
  "Sealed Concrete",
  "Anti-Static Flooring",
  "Rubberized Flooring",
  "Hardwood Flooring",
  "Porcelain Tiles",
  "Ceramic Tiles",
  "Linoleum Flooring",
  "Epoxy Flooring",
  "Rubber Flooring Tiles",
  "Laminate Flooring",
  "Terrazzo Flooring",
  "Bamboo Flooring",
  "Polished Concrete",
  "Natural Stone Flooring",
  "Vinyl Plank Flooring",
  "Quartz Flooring",
  "Marble Flooring",
  "Granite Flooring",
  "Slate Flooring",
  "Travertine Flooring",
  "Cork Flooring",
  "Glass Flooring",
  "Metal Flooring",
  "Leather Flooring",
];

const Wall = [
  "Select",
  "Drywall (Gypsum Board)",
  "Concrete Block Walls",
  "Cinder Block Walls",
  "Painted Concrete Walls",
  "Metal Stud Walls",
  "Glass Walls (for Data Center Viewing)",
  "Glass Block Walls",
  "Brick Walls",
  "Vinyl Wall Coverings",
  "Wood Paneling",
  "Acoustic Wall Panels",
  "Steel Cladding Panels",
  "Fiberglass Reinforced Panels (FRP)",
  "Fabric Wall Panels",
  "Cement Board Walls",
  "Plaster Walls",
  "Tile Walls",
  "Stone Veneer Walls",
  "Solid Glass Walls (for Aesthetics)",
  "Polycarbonate Walls",
  "Perforated Metal Walls (for Ventilation)",
  "Metallic Finish Walls",
  "Vinyl Wall Graphics",
  "Mirror Walls",
  "Chalkboard or Whiteboard Walls",
  "Custom Wall Art or Murals",
  "Bamboo Wall Coverings",
  "Digital Print Walls",
  "Magnetic Walls (for Note-Taking)",
  "Green Wall (Living Plant Wall)",
  // Add more types as needed
];

const Reader = [
  "Select",
  "Magnetic Stripe Card Reader",
  "Proximity Card Reader",
  "Smart Card Reader (Contact)",
  "Smart Card Reader (Contactless)",
  "Biometric Fingerprint Scanner",
  "Keypad PIN Entry",
  "Barcode Scanner",
  "RFID Card Reader",
  "Bluetooth Card Reader",
  "Facial Recognition Scanner",
];

const Door = [
  "Select",
  "Solid Metal Door",
  "Glass Door with Access Control",
  "Security Access Gate",
  "Fire-Rated Door",
  "Biometric Entry Door",
  "Key Card Entry Door",
  "Emergency Exit Door",
  "Double-Sliding Doors",
  "Server Room Airlock Door",
  "Soundproofed Door",
];

const Fire = [
  "Select",
  "Smoke Detectors (Ionization)",
  "Smoke Detectors (Photoelectric)",
  "Heat Detectors (Fixed Temperature)",
  "Heat Detectors (Rate-of-Rise)",
  "Flame Detectors (Ultraviolet)",
  "Flame Detectors (Infrared)",
  "Gas Detectors (Carbon Monoxide)",
  "Gas Detectors (Natural Gas)",
  "Beam Detectors (Projected Beam)",
  "Aspirating Smoke Detection",
];

const FireSuppression = [
  "Select",
  "Water Sprinkler System",
  "Clean Agent (Halon Replacement) System",
  "CO2 (Carbon Dioxide) System",
  "Foam-Based Fire Suppression System",
  "Dry Chemical Fire Suppression System",
  "Wet Chemical Fire Suppression System (Kitchen Hood)",
  "Pre-Action Sprinkler System",
  "Deluge Sprinkler System",
  "Inert Gas Fire Suppression System (IG-55, IG-541)",
  "Water Mist Fire Suppression System",
];

export { Ceiling, Floor, Wall, Reader, Door, Fire, FireSuppression };
