import countries from "./TemplateHelpers/Counties";
import * as Survey from "./TemplateHelpers/SurveyArrays";
import CreateTemplatesAssets from "../../Comp/Aduit/AddNew/CreateTemplatesAssets";
import CreateTemplatesRacks from "../../Comp/Aduit/AddNew/CreateNewTemplatesRacks";
import CreateTemplatesPDU from "../../Comp/Aduit/AddNew/CreateTemplatesPDU";

//* ADD OR REMOVE OPTIONS FROM THE DROP DOWNS WHEN ADDING DATA
//* ie: ADD ROW => ADD TO OPTION IN THE CABINET DROP DOWN

let Template = {
  Location: {
    ///////////////
    "# Operation *": { value: "ADD" },
    "Object *": { value: "LOCATION" },
    "dcTrack Location Code *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "dcTrack Location Name *": {
      type: "text",
      value: "",

      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "dcTrack Location Hierarchy *": {
      type: "select",
      value: "",

      placeholder: "Input Here",
      options: ["Data Center", "Floor", "Room"],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "dcTrack Location Parent": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Data Center Area *": {
      type: "number",
      value: 0,

      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Country *": {
      type: "select",
      value: "",

      options: countries,
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Status *": { value: "PLANNED" },
  },
  //////////////////
  Rooms: {
    "# Operation *": { value: "ADD" },
    "Object *": { value: "SUBLOCATION" },
    "Sub Location Type *": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: ["Select", "Aisle", "Row"],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Sub Location Name *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Location *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      disabled: true,
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },

    "Parent Sub Location": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Capacity(kW)": {
      type: "number",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
  },
  //////////////////
  Racks: {
    "# Operation *": { value: "ADD" },
    "Object *": { value: "CABINET" },
    "!!!OpenRUArray": {
      value: [],
    },
    "Name *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Make *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "Make",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Model *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "Model",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "RU Height": {
      type: "number",
      value: 1,
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: true,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Part Number": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Location *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      disabled: true,
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Front Faces": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: ["Select", "North", "South", "East", "West"],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    // "Aisle Label": {
    //   type: "Programmed",
    //   value: "",
    //   required: false,
    //   NEXT: "HOLD FOR ADDITIONAL INFO",
    // },
    // "Row Label **": {
    //   type: "Programmed",
    //   value: "",
    //   required: false,
    //   NEXT: "HOLD FOR ADDITIONAL INFO",
    // },
    // "Position in Row **": {
    //   type: "number",
    //   value: "",
    //   placeholder: "Input Here",
    //   options: [],
    //   required: false,
    //   APIMatch: "",
    //   NEXT: "HOLD FOR ADDITIONAL INFO",
    // },
    "Power Capacity (kW)": {
      type: "number",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Weight Capacity": {
      type: "number",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Status *": { value: "PLANNED" },
  },
  //////////////////
  PDUs: {
    "# Operation *": { value: "ADD" },
    "Object *": { value: "Rack PDU" },
    "Name *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
    },
    "Make *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "Make",
    },
    "Model *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "Model",
    },
    "Location *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      disabled: true,
      required: false,
      APIMatch: "",
    },
    "Cabinet *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: true,
      APIMatch: "",
    },
    "Cabinet Side *": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: ["Select", "Left Side", "Right Side"],
      required: false,
      APIMatch: "",
    },
    "Depth Position *": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: ["Select", "Front", "Center", "Back"],
      required: false,
      APIMatch: "",
    },
    "U Position *": {
      type: "number",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      aPIMatch: "",
    },
    "RU Height": {
      type: "number",
      value: 1,
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: true,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Status *": { value: "PLANNED" },
  },
  //////////////////
  Assets: {
    "# Operation *": { value: "ADD" },
    "Object *": "DEVICE-RACKABLE",
    "Name *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Make *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "Make",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Model *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "Model",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Location *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: true,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Cabinet *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: true,
      APIMatch: "",
    },
    "U Position *": {
      type: "number",
      value: 0,
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "RU Height": {
      type: "number",
      value: 1,
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: true,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Asset Tag": {
      type: "Scan",
      value: "",
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Rails Used *": {
      type: "select",
      value: "",
      options: ["Select", "Both", "Front", "Back"],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },

    "Orientation *": {
      type: "select",
      value: "",
      options: ["Select", "Item Rear Faces Cabinet Front", "Item Front Faces Cabinet Front"],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Status *": { value: "PLANNED" },
  },
  //////////////////
  SurveyRoom: {
    "Room Number *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
    },
    "GPS Coordinates *": {
      type: "GPS",
      value: "GPS Coordinates",
      placeholder: "GPS Coordinates",
      options: [],
      required: false,
      APIMatch: "",
    },
    "Area *": {
      type: "number",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
    },
    "Ceiling Type *": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: Survey.Ceiling,
      required: false,
      APIMatch: "",
    },
    "Ceiling Condition *": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: ["Select", "Good", "Fair", "Poor", "Water Damage", "Gaps"],
      required: false,
      APIMatch: "",
    },
    "Floor Type *": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: Survey.Floor,
      required: false,
      APIMatch: "",
    },
    "Floor Condition *": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: ["Select", "Good", "Fair", "Poor", "Water Damage", "Gaps"],
      required: false,
      APIMatch: "",
    },
    "Wall Type *": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: Survey.Wall,
      required: false,
      APIMatch: "",
    },
    "Wall Condition *": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: ["Select", "Good", "Fair", "Poor", "Water Damage", "Gaps"],
      required: false,
      APIMatch: "",
    },
    "Cleanliness *": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: ["Select", "Clean", "Dirty"],
      required: false,
      APIMatch: "",
    },
    "Room Notes": {
      type: "textarea",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
    },
  },
  //////////////////
  SurveySecurity: {
    "Key Lock *": {
      type: "bool",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
    },
    "Key Pad *": {
      type: "bool",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
    },
    "Badge Reader *": {
      type: "bool",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
    },
    "Reader Type *": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: Survey.Reader,
      required: false,
      APIMatch: "",
    },
    "Camera *": {
      type: "bool",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
    },
    "Camera Angle *": {
      type: "number",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
    },
    "Door Type *": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: Survey.Door,
      required: false,
      APIMatch: "",
    },
    "Door Secure *": {
      type: "bool",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
    },
    "Security Notes *": {
      type: "textarea",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
    },
  },
  //////////////////
  SurveyFire: {
    "Fire Detection *": {
      type: "bool",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
    },
    "Fire Detection Type": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: Survey.Fire,
      required: false,
      APIMatch: "",
    },
    "Fire Suppression *": {
      type: "bool",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
    },
    "Fire Suppression Type": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: Survey.FireSuppression,
      required: false,
      APIMatch: "",
    },
    "Fire Walls *": {
      type: "bool",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
    },
    "Fire Wall Rating": {
      type: "number",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
    },
    "Fire Notes": {
      type: "textarea",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
    },
  },
  NewAssets: CreateTemplatesAssets,
  NewRacks: CreateTemplatesRacks,
  NewPDUs: CreateTemplatesPDU,
};

const state = {
  Location: [Template.Location],
  // Rooms: [],
  Racks: [],
  PDUs: [],
  Assets: [],
  LoggedIn: false,
  Settings: {
    localStorage: true,
  },
  OpenRU: [],
  Current: {
    Location: 0,
    Rooms: 0,
    Racks: 0,
    PDUs: 0,
    Assets: 0,
    NewRacks: 0,
    NewPDUs: 0,
    NewAssets: 0,
    SurveyRoom: 0,
    SurveySecurity: 0,
    SurveyFire: 0,
  },
  NewRacks: [],
  NewPDUs: [],
  NewAssets: [],
  SurveyRoom: [Template.SurveyRoom],
  SurveySecurity: [Template.SurveySecurity],
  SurveyFire: [Template.SurveyFire],
  // Survey: {
  //   Location: [],
  //   Rooms: [],
  //   Racks: [],
  //   Assets: [],
  // },
};

export default Template;
export { state };

// let text = {
//   type: "text",
//   value: "",
//   placeholder: "Input Here",
//   options: [],
//   required: false,
//   APIMatch: "",
//   NEXT: "HOLD FOR ADDITIONAL INFO",
// };

// let number = {
//   type: "number",
//   value: 0,
//   options: [],
//   required: false,
//   aPIMatch: "",
//   NEXT: "HOLD FOR ADDITIONAL INFO",
// };

// let date = {
//   type: "date",
//   value: "2007-06-09",
//   options: [],
//   required: false,
//   aPIMatch: "",
//   NEXT: "HOLD FOR ADDITIONAL INFO",
// };

// let bool = {
//   type: "bool",
//   value: false,
//   options: [],
//   required: false,
//   aPIMatch: "",
//   NEXT: "HOLD FOR ADDITIONAL INFO",
// };

// let select = {
//   type: "select",
//   value: "",
//   options: [],
//   required: false,
//   aPIMatch: "",
//   NEXT: "HOLD FOR ADDITIONAL INFO",
// };
