import countries from "./TemplateHelpers/Counties";
import * as Elect from "./TemplateHelpers/ElectricalArrays";
import * as Survey from "./TemplateHelpers/SurveyArrays";
import CreateTemplatesAssets from "../../Comp/Aduit/AddNew/CreateTemplatesAssets";
import CreateTemplatesRacks from "../../Comp/Aduit/AddNew/CreateNewTemplatesRacks";
import CreateTemplatesPDU from "../../Comp/Aduit/AddNew/CreateTemplatesPDU";

//* ADD OR REMOVE OPTIONS FROM THE DROP DOWNS WHEN ADDING DATA
//* ie: ADD ROW => ADD TO OPTION IN THE CABINET DROP DOWN

let Template = {
  Location: {
    ///////////////
    "# Operation *": { value: "ADD", Export: "# Operation *" },
    "Object *": { value: "LOCATION", Export: "Object *" },
    "dcTrack Location Code *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "dcTrack Location Code *",
    },
    "dcTrack Location Name *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "dcTrack Location Name *",
    },
    "dcTrack Location Hierarchy *": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: ["Data Center", "Floor", "Room"],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "dcTrack Location Hierarchy *",
    },
    "dcTrack Location Parent": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "dcTrack Location Parent",
    },
    "Data Center Area *": {
      type: "number",
      value: 0,
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Data Center Area *",
    },
    "Country *": {
      type: "select",
      value: "",
      options: countries,
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Country *",
    },
    "Custom Field Testing 1 *": {
      type: "number",
      value: 555,
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "Status *": { value: "PLANNED", Export: "Status *" },
  },
  //////////////////
  // Rooms: {
  //   "# Operation *": { value: "ADD" },
  //   "Object *": { value: "SUBLOCATION" },
  //   "Sub Location Type *": {
  //     type: "select",
  //     value: "",
  //     placeholder: "Input Here",
  //     options: ["Select", "Aisle", "Row"],
  //     required: false,
  //     APIMatch: "",
  //     NEXT: "HOLD FOR ADDITIONAL INFO",
  //     Export: "",
  //   },
  //   "Sub Location Name *": {
  //     type: "text",
  //     value: "",
  //     placeholder: "Input Here",
  //     options: [],
  //     required: false,
  //     APIMatch: "",
  //     NEXT: "HOLD FOR ADDITIONAL INFO",
  //     Export: "",
  //   },
  //   "Location *": {
  //     type: "text",
  //     value: "",
  //     placeholder: "Input Here",
  //     options: [],
  //     disabled: true,
  //     required: false,
  //     APIMatch: "",
  //     NEXT: "HOLD FOR ADDITIONAL INFO",
  //     Export: "",
  //   },

  //   "Parent Sub Location": {
  //     type: "text",
  //     value: "",
  //     placeholder: "Input Here",
  //     options: [],
  //     required: false,
  //     APIMatch: "",
  //     NEXT: "HOLD FOR ADDITIONAL INFO",
  //     Export: "",
  //   },
  //   "Capacity(kW)": {
  //     type: "number",
  //     value: "",
  //     placeholder: "Input Here",
  //     options: [],
  //     required: false,
  //     APIMatch: "",
  //     NEXT: "HOLD FOR ADDITIONAL INFO",
  //     Export: "",
  //   },
  // },
  //////////////////
  Racks: {
    "# Operation *": { value: "ADD", Export: "# Operation *" },
    "Object *": { value: "CABINET", Export: "Object *" },
    "Name *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Name *",
    },
    "Make *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "Make",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Make *",
    },
    "Model *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "Model",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Model *",
    },
    "RU Height": {
      type: "number",
      value: 1,
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: true,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "Location *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      disabled: true,
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Location *",
    },
    "Front Faces": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: ["Select", "North", "South", "East", "West"],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Front Faces",
    },
    // "Aisle Label": {
    //   type: "Programmed",
    //   value: "",
    //   required: false,
    //   NEXT: "HOLD FOR ADDITIONAL INFO", Export: "",
    // },
    // "Row Label **": {
    //   type: "Programmed",
    //   value: "",
    //   required: false,
    //   NEXT: "HOLD FOR ADDITIONAL INFO", Export: "",
    // },
    // "Position in Row **": {
    //   type: "number",
    //   value: "",
    //   placeholder: "Input Here",
    //   options: [],
    //   required: false,
    //   APIMatch: "",
    //   NEXT: "HOLD FOR ADDITIONAL INFO", Export: "",
    // },
    "Asset Tag": {
      type: "Scan",
      value: "",
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Asset Tag",
    },
    "Status *": { value: "PLANNED", Export: "Status *" },
  },
  //////////////////
  PDUs: {
    "# Operation *": { value: "ADD", Export: "# Operation *" },
    "Object *": { value: "Rack PDU", Export: "Object *" },
    "Name *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      Export: "Name *",
    },
    "Make *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "Make",
      Export: "Make *",
    },
    "Model *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "Model",
      Export: "Model *",
    },
    "Location *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      disabled: true,
      required: false,
      APIMatch: "",
      Export: "Location *",
    },
    "Cabinet *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: true,
      APIMatch: "",
      Export: "Cabinet **",
    },
    "Cabinet Side *": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: ["Select", "Left", "Right"],
      required: false,
      APIMatch: "",
      Export: "Cabinet Side **",
    },
    "Depth Position *": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: ["Select", "Front", "Center", "Back"],
      required: false,
      APIMatch: "",
      Export: "Depth Position **",
    },
    "U Position *": {
      type: "number",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      aPIMatch: "",
      Export: "U Position **",
    },
    "RU Height": {
      type: "number",
      value: 1,
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: true,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },

    Ports: {
      type: "number",
      value: 0,
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: false,
      APIMatch: "DataPortsCount",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    Mounting: {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "Slots Front": {
      type: "number",
      value: 0,
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: false,
      APIMatch: "DataPortsCount",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "Slots Back": {
      type: "number",
      value: 0,
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: false,
      APIMatch: "DataPortsCount",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "Asset Tag": {
      type: "Scan",
      value: "",
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Asset Tag",
    },
    "Status *": { value: "PLANNED" },
  },
  //////////////////
  Assets: {
    "# Operation *": { value: "ADD", Export: "# Operation *" },
    "Object *": { value: "DEVICE-RACKABLE", Export: "Object *" },
    "Name *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Name *",
    },
    "Make *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "Make",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Make *",
    },
    "Model *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "Model",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Model *",
    },
    "Location *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: true,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Location *",
    },
    "Cabinet *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: true,
      APIMatch: "Cabinet *",
      Export: "Cabinet *",
    },
    "U Position *": {
      type: "number",
      value: 0,
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "U Position *",
    },
    "RU Height": {
      type: "number",
      value: 1,
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: true,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "Asset Tag": {
      type: "Scan",
      value: "",
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Asset Tag",
    },
    "Rails Used *": {
      type: "select",
      value: "",
      options: ["Select", "Both", "Front", "Back"],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Rails Used *",
    },
    "Orientation *": {
      type: "select",
      value: "",
      options: ["Select", "Item Rear Faces Cabinet Front", "Item Front Faces Cabinet Front"],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Orientation *",
    },
    Ports: {
      type: "number",
      value: 0,
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: false,
      APIMatch: "DataPortsCount",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    Mounting: {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "Slots Front": {
      type: "number",
      value: 0,
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: false,
      APIMatch: "DataPortsCount",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "Slots Back": {
      type: "number",
      value: 0,
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: false,
      APIMatch: "DataPortsCount",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "Status *": { value: "PLANNED", Export: "Status" },
  },
  Blades: {
    "# Operation *": { value: "ADD", Export: "# Operation *" },
    "Object *": { value: "DEVICE-BLADE", Export: "Object *" },
    "Name *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Name *",
    },
    "Make *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "Make",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Make *",
    },
    "Model *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "Model",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Model *",
    },
    "Location *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: true,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Location *",
    },
    "Cabinet *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: true,
      APIMatch: "Cabinet *",
      Export: "Cabinet *",
    },
    "Chassis *": {
      type: "text",
      value: 0,
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Chassis *",
    },
    "Asset Tag": {
      type: "Scan",
      value: "",
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Asset Tag",
    },
    "Chassis Face *": {
      type: "select",
      value: "",
      options: ["Select", "Front", "Back"],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Chassis Face *",
    },
    "Slot Position *": {
      type: "number",
      value: 0,
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Slot Position *",
    },
    Ports: {
      type: "number",
      value: 0,
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: false,
      APIMatch: "DataPortsCount",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    Mounting: {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "Status *": { value: "PLANNED", Export: "Status" },
  },
  //////////////////
  UPSs: {
    "# Operation *": { value: "ADD" },
    // "Object *": "DEVICE-RACKABLE",
    "Object *": { value: "DEVICE-RACKABLE" },
    "Name *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "Make *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "Make",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "Model *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "Model",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "Location *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: true,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "Cabinet *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: true,
      APIMatch: "",
    },
    "Location Type": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: true,
      APIMatch: "",
    },
    "U Position *": {
      type: "number",
      value: 0,
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "RU Height": {
      type: "number",
      value: 1,
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: true,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "kw Rating *": {
      type: "number",
      value: 0,
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "Utilized kw": {
      type: "number",
      value: 0,
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "Network connected": {
      type: "bool",
      value: false,
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "Asset Tag": {
      type: "Scan",
      value: "",
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "Total connections": {
      type: "number",
      value: 0,
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "Type of Connections": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: ["Select", "Copper", "Fiber"],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    Ports: {
      type: "number",
      value: 0,
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: false,
      APIMatch: "DataPortsCount",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    Mounting: {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "Slots Front": {
      type: "number",
      value: 0,
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: false,
      APIMatch: "DataPortsCount",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "Slots Back": {
      type: "number",
      value: 0,
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: false,
      APIMatch: "DataPortsCount",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
  },
  StructuredCabling: {
    "# Operation *": { value: "ADD", Export: "# Operation *" },
    "Object *": { value: "STRUCTURED-CABLING", Export: "Object *" },
    "Starting Item Location *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: true,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Starting Item Location *",
    },
    "Starting Item Name *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: true,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Starting Item Name *",
    },
    "Starting Port Name *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: true,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Starting Port Name *",
    },
    "Starting Port Index *": {
      type: "number",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: true,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Starting Port Index *",
    },
    "Starting Port Connector *": {
      type: "select",
      value: "RJ45",
      placeholder: "Input Here",
      options: ["Select", "RJ45", "LC", "SC", "ST", "MPO"],
      required: false,
      disabled: true,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Starting Port Connector *",
    },
    "Cable Grade *": {
      type: "select",
      value: "Cat6",
      placeholder: "Input Here",
      options: ["Select", "Cat5e", "Cat6", "Cat6A", "Cat7", "Cat8"],
      required: false,
      disabled: true,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Cable Grade *",
    },
    "Media **": {
      type: "select",
      value: "Twisted Pair",
      placeholder: "Input Here",
      options: ["Select", "Twisted Pair", "Fiber"],
      required: false,
      disabled: true,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Media **",
    },
    "Length (ft/m) *": {
      type: "number",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: true,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Length (ft/m) *",
    },
    "Length Units *": {
      type: "select",
      value: "US",
      placeholder: "Input Here",
      options: ["Select", "US", "Metric"],
      required: false,
      disabled: true,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Length Units *",
    },
    "Color *": {
      type: "select",
      value: "Blue",
      placeholder: "Input Here",
      options: ["Select", "Blue", "Green", "Yellow", "Orange", "Purple", "White", "Black"],
      required: false,
      disabled: true,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Color *",
    },
    "Ending Item Location *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: true,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Ending Item Location *",
    },
    "Ending Item Name *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: true,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Ending Item Name *",
    },
    "Ending Port Name *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: true,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Ending Port Name *",
    },
    "Ending Port Index *": {
      type: "number",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: true,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Ending Port Index *",
    },
    "Ending Port Connector *": {
      type: "select",
      value: "RJ45",
      placeholder: "Input Here",
      options: ["Select", "RJ45", "LC", "SC", "ST", "MPO"],
      required: false,
      disabled: true,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "Ending Port Connector *",
    },
    "Connection Data": {
      Display: false,
      Connected: true,
      StartingItem: "",
      StartingPort: "",
      EndingItem: "",
      EndingPort: "",
      Export: "",
    },
  },
  //////////////////
  ATSs: {
    "# Operation *": { value: "ADD" },
    // "Object *": "DEVICE-RACKABLE",
    "Object *": { value: "DEVICE-RACKABLE" },
    "Name *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "Make *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "Make",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "Model *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "Model",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "Location *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: true,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "Cabinet *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: true,
      APIMatch: "",
    },
    "Location Type": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: true,
      APIMatch: "",
    },
    "U Position *": {
      type: "number",
      value: 0,
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "RU Height": {
      type: "number",
      value: 1,
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: true,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "kw Rating *": {
      type: "number",
      value: 0,
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "Utilized kw": {
      type: "number",
      value: 0,
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "Network connected": {
      type: "bool",
      value: false,
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "Asset Tag": {
      type: "Scan",
      value: "",
      options: [],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "Total connections": {
      type: "number",
      value: 0,
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    "Type of Connections": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: ["Select", "Copper", "Fiber"],
      required: false,
      aPIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    Ports: {
      type: "number",
      value: 0,
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: false,
      APIMatch: "DataPortsCount",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    Mounting: {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
    Slots: {
      type: "number",
      value: 0,
      Front: 0,
      Back: 0,
      placeholder: "Input Here",
      options: [],
      required: false,
      disabled: false,
      APIMatch: "DataPortsCount",
      NEXT: "HOLD FOR ADDITIONAL INFO",
      Export: "",
    },
  },
  //////////////////
  Panels: {
    "# Operation *": { value: "ADD" },
    // "Object *": "DEVICE-RACKABLE",
    "Object *": { value: "DEVICE-RACKABLE" },
    "Name *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
    },
    "Location *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      disabled: true,
      required: false,
      APIMatch: "",
    },
    "Upstream Connection": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: Elect.Upstream,
      required: false,
      APIMatch: "",
    },
  },
  //////////////////
  Receptacles: {
    "# Operation *": { value: "ADD" },
    // "Object *": "DEVICE-RACKABLE",
    "Object *": { value: "DEVICE-RACKABLE" },
    "Location *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      disabled: true,
      required: false,
      APIMatch: "",
    },
    Placement: {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: ["Select", "Cabinet", "Wall"],
    },
    "Cabinet Placement": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
    },
    "Wall Placement": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
    },
  },
  SurveySite: {
    "Survey Date": {
      type: "date",
      value: "",
      placeholder: "dd/mm/yyyy",
      options: [],
      required: true,
      check: "Date of survey in dd/mm/yyyy format",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Company Surveying": {
      type: "text",
      value: "",
      placeholder: "Company Name",
      options: [],
      required: true,
      check: "Name of company performing survey",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Survey Tech Name": {
      type: "text",
      value: "",
      placeholder: "Tech Name",
      options: [],
      required: true,
      check: "MDF/IDF Survey Tech name",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Survey Tech Phone": {
      type: "text",
      value: "",
      placeholder: "Tech Phone",
      options: [],
      required: true,
      check: "MDF/IDF Survey Tech contact number",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Survey Tech Email": {
      type: "text",
      value: "",
      placeholder: "Tech Email",
      options: [],
      required: true,
      check: "MDF/IDF Survey Tech email address",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    Site: {
      type: "text",
      value: "",
      placeholder: "Site Name",
      options: [],
      required: true,
      check: "Site Name",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    Building: {
      type: "text",
      value: "",
      placeholder: "Building Name",
      options: [],
      required: true,
      check: "Building Name",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    Floor: {
      type: "text",
      value: "",
      placeholder: "Floor Number",
      options: [],
      required: true,
      check: "Floor Number",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "ATG Room Number": {
      type: "text",
      value: "",
      placeholder: "Room Number",
      options: [],
      required: true,
      check: "Room Number",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "ATG Room Name": {
      type: "text",
      value: "",
      placeholder: "Room Name",
      options: [],
      required: true,
      check: "Room Name",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Alias Room Name": {
      type: "text",
      value: "",
      placeholder: "Room Name",
      options: [],
      required: true,
      check: "Alias or Prior Historic Name",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    Barcode: {
      type: "text",
      value: "",
      placeholder: "If Different From ATG Room Number",
      options: [],
      required: true,
      check: "Barcode: If Different From ATG Room Number",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Survey Tech Role": {
      type: "select",
      value: "",
      placeholder: "",
      options: ["Client Staff - Non Technical", "Client Staff Technical", "Client Venders"],
      required: true,
      check: "MDF/IDF Survey Tech Role",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Site Type": {
      type: "select",
      value: "",
      placeholder: "",
      options: ["Acute", "Health Center", "Clinic", "Corp Office"],
      required: true,
      check: "Type of Site being surveyed",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Site Name": {
      type: "text",
      value: "",
      placeholder: "Name of Site being surveyed",
      options: [],
      required: true,
      check: "If blank manually enter site name or update Master Site List worksheet",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Site Address": {
      type: "text",
      value: "",
      placeholder: "Address of Site being surveyed",
      options: [],
      required: true,
      check: "If blank manually enter address or update Master Site List worksheet",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Site Country": {
      type: "text",
      value: "",
      placeholder: "Country of Site being surveyed",
      options: [],
      required: true,
      check: "If blank manually enter country or update Master Site List worksheet",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Local Site Contact": {
      type: "text",
      value: "",
      placeholder: "Name of local site contact",
      options: [],
      required: true,
      check: "If blank manually enter site contact or update Master Site List worksheet",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Site Contact Role": {
      type: "select",
      value: "",
      placeholder: "",
      options: ["Client Staff - Non Technical", "Client Staff Technical"],
      required: true,
      check: "Role of local site contact",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Site Contact Email": {
      type: "text",
      value: "",
      placeholder: "Email of local site contact",
      options: [],
      required: true,
      check: "If blank manually enter site contacts role or update Master Site List worksheet",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Site Contact Phone": {
      type: "text",
      value: "",
      placeholder: "Phone of local site contact",
      options: [],
      required: true,
      check: "If blank manually enter site contacts phone or update Master Site List worksheet",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
    "Access Times": {
      type: "text",
      value: "",
      placeholder: "Access times for site",
      options: [],
      required: true,
      check: "Details of access times",
      NEXT: "HOLD FOR ADDITIONAL INFO",
    },
  },
  SurveyGlobal: {
    "Key Holder Record": {
      type: "select",
      value: "Not Started",
      placeholder: "Input Here",
      options: ["Not Started", "Complete", "In Process"],
      required: true,
      check: "Record of who has keys to MDF/IDF doors",
      information: "Is there a record of key holders?",
      regulatory: "Y",
      notes: "",
    },
    "Access Records": {
      type: "select",
      value: "Not Started",
      placeholder: "Input Here",
      options: ["Not Started", "Complete", "In Process"],
      required: true,
      check: "Are the door records available via Lenel?",
      information: "Is there a procedure for review?",
      regulatory: "Y",
      notes: "",
    },
    "Visitor Access Records": {
      type: "select",
      value: "Not Started",
      placeholder: "Input Here",
      options: ["Not Started", "Complete", "In Process"],
      required: true,
      check: "Are visitor access records kept",
      information: "Did you have to sign in?",
      regulatory: "Y",
      notes: "",
    },
    "Visitor Log Contains": {
      type: "select",
      value: "Not Started",
      placeholder: "Input Here",
      options: ["Not Started", "Complete", "In Process"],
      required: true,
      check: "Is there a visitor log?",
      information: "Name, Company, Authorizer- minimum",
      regulatory: "Y",
      notes: "",
    },
    "Visitor Log Retention": {
      type: "select",
      value: "Not Started",
      placeholder: "Input Here",
      options: ["Not Started", "Complete", "In Process"],
      required: true,
      check: "Are there 3 months of Visitor Logs retained??",
      information: "3 months retention required",
      regulatory: "Y",
      notes: "",
    },
    "Auto Expiring Badges": {
      type: "select",
      value: "Not Started",
      placeholder: "Input Here",
      options: ["Not Started", "Complete", "In Process"],
      required: true,
      check: "Is an auto expiring badge used for site access?",
      information: "Can they identify an old/reused badge",
      regulatory: "Y",
      notes: "",
    },
    "Visitor Escort Required": {
      type: "select",
      value: "Not Started",
      placeholder: "Input Here",
      options: ["Not Started", "Complete", "In Process"],
      required: true,
      check: "Is a visitor escort required?",
      information: "Is there a procedure for escorting visitors?",
      regulatory: "Y",
      notes: "",
    },
  },
  //////////////////
  SurveyRoom: {
    "Room Number *": {
      type: "text",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
    },
    "GPS Coordinates *": {
      type: "GPS",
      value: "GPS Coordinates",
      placeholder: "GPS Coordinates",
      options: [],
      required: false,
      APIMatch: "",
    },
    "Area *": {
      type: "number",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
    },

    "WiFi Access": {
      type: "select",
      value: "",
      placeholder: "WiFi access in the room",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = WiFi access is available in the room",
      Appendix: "",
      information: "",
      regulatory: "",
      notes: "",
      scoreWeigh: 0,
      score: 0,
      valueXLate: 5,
    },
    "Cell Reception": {
      type: "select",
      value: "",
      placeholder: "Check carrier and strength",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = Reasonable Cell reception. Indicate carrier in Notes column",
      Appendix: "",
      information: "",
      regulatory: "",
      notes: "",
      scoreWeigh: 0,
      score: 0,
      valueXLate: 5,
    },
    "Data Panel Grade *": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: ["Cat5e", "Cat6", "Cat6a", "Cat7", "Cat8", "OM1", "OM2", "OM3", "OM4", "OS2"],
      required: false,
      APIMatch: "",
    },
    Busbar: {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: ["Select", "Yes", "No"],
      required: false,
      APIMatch: "",
    },
    "Ceiling Type *": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: Survey.Ceiling,
      required: false,
      APIMatch: "",
    },
    "Ceiling Condition *": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: ["Select", "Good", "Fair", "Poor", "Water Damage", "Gaps"],
      required: false,
      APIMatch: "",
    },
    "Floor Type *": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: Survey.Floor,
      required: false,
      APIMatch: "",
    },
    "Floor Condition *": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: ["Select", "Good", "Fair", "Poor", "Water Damage", "Gaps"],
      required: false,
      APIMatch: "",
    },
    "Wall Type *": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: Survey.Wall,
      required: false,
      APIMatch: "",
    },
    "Wall Condition *": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: ["Select", "Good", "Fair", "Poor", "Water Damage", "Gaps"],
      required: false,
      APIMatch: "",
    },
    "Cleanliness *": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: ["Select", "Clean", "Fair", "Dirty"],
      required: false,
      APIMatch: "",
    },
    "Room Notes": {
      type: "textarea",
      value: "",
      placeholder: "Input Here",
      options: [],
      required: false,
      APIMatch: "",
    },
  },
  //////////////////
  SurveySecurity: {
    "Access Door Control": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = Standard Badge Reader on access door that functions",
      Appendix: "C",
      information: "",
      regulatory: "Y",
      notes: "",
      scoreWeigh: 0,
      score: 0,
      valueXLate: 5,
    },
    "Is the Room Secure?": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = any access (all doors, gaps) to room controlled by card reader",
      Appendix: "",
      information: "",
      regulatory: "Y",
      notes: "",
      scoreWeigh: 0,
      score: 0,
      valueXLate: 5,
    },
    "Available Key Access": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = key slot in the door handle",
      Appendix: "",
      information: "",
      regulatory: "Y",
      notes: "",
      scoreWeigh: 0,
      score: 0,
      valueXLate: 5,
    },
    "Door Manual Unlocking": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = door is permanently locked",
      Appendix: "",
      information: "",
      regulatory: "Y",
      notes: "",
      scoreWeigh: 0,
      score: 0,
      valueXLate: 5,
    },
    "Avigilon camera Present?": {
      type: "select",
      value: "",
      placeholder: "Input Here",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = the room has an Aviligilon camera (Appendix C)",
      Appendix: "C",
      information: "",
      regulatory: "Y",
      notes: "",
      scoreWeigh: 0,
      score: 0,
      valueXLate: 5,
    },
    "2 Post Racks Secured Floor": {
      type: "select",
      value: "",
      placeholder: "2-Post rack secured to floor",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = Secured to floor",
      Appendix: "",
      information: "",
      regulatory: "",
      notes: "",
      scoreWeigh: 10,
      score: 50,
      valueXLate: 5,
    },
    "2 Post Racks Secured Ladder": {
      type: "select",
      value: "",
      placeholder: "2-post rack secured to ladder rack",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = Secured to LAdder rack",
      Appendix: "",
      information: "",
      regulatory: "",
      notes: "",
      scoreWeigh: 10,
      score: 50,
      valueXLate: 5,
    },
    "4 Post Racks Moving": {
      type: "select",
      value: "",
      placeholder: "4-post rack wheel locks",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = Jacks lowered to prevent rack from moving",
      Appendix: "",
      information: "",
      regulatory: "",
      notes: "",
      scoreWeigh: 10,
      score: 50,
      valueXLate: 5,
    },
    "Vertical Wire Capacity": {
      type: "select",
      value: "",
      placeholder: "Check spare vertical space",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = 50% or more capacity remains",
      Appendix: "",
      information: "",
      regulatory: "",
      notes: "",
      scoreWeigh: 10,
      score: 30,
      valueXLate: 3,
    },
    "Horizontal Wire Capacity": {
      type: "select",
      value: "",
      placeholder: "Check spare horizontal space",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = 50% or more capacity remains",
      Appendix: "",
      information: "",
      regulatory: "",
      notes: "",
      scoreWeigh: 10,
      score: 30,
      valueXLate: 3,
    },
    "Panels Fully Secured": {
      type: "select",
      value: "",
      placeholder: "Devices mounted correctly",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = all devices mounted correctly, Does not comply = equipment sitting on other equipment not secured",
      Appendix: "",
      information: "",
      regulatory: "",
      notes: "",
      scoreWeigh: 10,
      score: 50,
      valueXLate: 5,
    },
    "Cable Routing Neat": {
      type: "select",
      value: "",
      placeholder: "Cables secured and routed",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = cable infrastructure meets standard",
      Appendix: "C",
      information: "",
      regulatory: "",
      notes: "",
      scoreWeigh: 10,
      score: 30,
      valueXLate: 3,
    },
    "Copper Patch Neat": {
      type: "select",
      value: "",
      placeholder: "Copper cable layout clean",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = copper patch cables are run neatly, and labeled per standard",
      Appendix: "",
      information: "",
      regulatory: "",
      notes: "",
      scoreWeigh: 10,
      score: 40,
      valueXLate: 4,
    },
    "Fiber LIU Correct": {
      type: "select",
      value: "",
      placeholder: "Fiber strain relief OK",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = All strain relief and service loops installed in LIU, not hanging",
      Appendix: "",
      information: "",
      regulatory: "",
      notes: "",
      scoreWeigh: 10,
      score: 50,
      valueXLate: 5,
    },
    "Loose Patch Cables": {
      type: "select",
      value: "",
      placeholder: "No loose patch cables",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = no 'loose ends dangling in rack'",
      Appendix: "",
      information: "",
      regulatory: "",
      notes: "",
      scoreWeigh: 10,
      score: 30,
      valueXLate: 3,
    },
    "Unpowered Rack Equipment": {
      type: "select",
      value: "",
      placeholder: "Check for unpowered devices",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = all equipment in rack is in production",
      Appendix: "",
      information: "",
      regulatory: "",
      notes: "",
      scoreWeigh: 10,
      score: 20,
      valueXLate: 2,
    },
    "Unpatched Powered Equipment": {
      type: "select",
      value: "",
      placeholder: "Check for idle powered gear",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = all equipment in rack is in production",
      Appendix: "",
      information: "",
      regulatory: "",
      notes: "",
      scoreWeigh: 10,
      score: 20,
      valueXLate: 2,
    },
    "Equipment Labeled Correctly": {
      type: "select",
      value: "",
      placeholder: "Verify label standards",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = equipment is labeled per standard",
      Appendix: "",
      information: "",
      regulatory: "",
      notes: "",
      scoreWeigh: 10,
      score: 40,
      valueXLate: 4,
    },
    "Cooling Ducts Clear": {
      type: "select",
      value: "",
      placeholder: "Check fan tray flow",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = all grates, openings fan trays free flowing",
      Appendix: "",
      information: "",
      regulatory: "",
      notes: "",
      scoreWeigh: 10,
      score: 30,
      valueXLate: 3,
    },

    "Wall Equipment Secured": {
      type: "select",
      value: "",
      placeholder: "Check for loose wall gear",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = no loose/hanging equipment on walls",
      Appendix: "",
      information: "",
      regulatory: "",
      notes: "",
      scoreWeigh: 10,
      score: 50,
      valueXLate: 5,
    },
    "Wall Equipment Labeled": {
      type: "select",
      value: "",
      placeholder: "Check wall equipment labels",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = all Infrastructure equipment labeled per standard",
      Appendix: "",
      information: "",
      regulatory: "",
      notes: "",
      scoreWeigh: 10,
      score: 40,
      valueXLate: 4,
    },
  },
  //////////////////
  SurveySafety: {
    "Fire Extinguishers?": {
      type: "select",
      value: "",
      placeholder: "Type of Extinguishers",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = an ABC dry chemical extinguisher in the room, note type in Notes column",
      Appendix: "",
      information: "",
      regulatory: "Y",
      notes: "",
      scoreWeigh: 0,
      score: 0,
      valueXLate: 2,
    },

    "Rack Temp Range": {
      type: "select",
      value: "",
      placeholder: "Front of each rack temp.",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = front of each rack temp. 68-77 degrees, record value in Notes column",
      Appendix: "",
      information: "",
      regulatory: "",
      notes: "",
      scoreWeigh: 0,
      score: 0,
      valueXLate: 5,
    },
    "Air Quality": {
      type: "select",
      value: "",
      placeholder: "Air freshness and dryness",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = Air fresh/Dry/Cool does not comply=Stale/Musty",
      Appendix: "",
      information: "",
      regulatory: "",
      notes: "",
      scoreWeigh: 10,
      score: 40,
      valueXLate: 4,
    },
    "Rack Lumens": {
      type: "select",
      value: "",
      placeholder: "Measure at front and back",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = > 500 lumens",
      Appendix: "",
      information: "",
      regulatory: "",
      notes: "",
      scoreWeigh: 10,
      score: 50,
      valueXLate: 5,
    },
    "Cold Air Direction": {
      type: "select",
      value: "",
      placeholder: "Air directed to front (cold side)",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = cool air flow is directed to front of rack (cold side)",
      Appendix: "",
      information: "",
      regulatory: "Y",
      notes: "",
      scoreWeigh: 10,
      score: 40,
      valueXLate: 4,
    },
    "HVAC Return": {
      type: "select",
      value: "",
      placeholder: "Return air at back (hot side)",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = Return air is at the back of rack (Hot side)",
      Appendix: "",
      information: "",
      regulatory: "",
      notes: "",
      scoreWeigh: 10,
      score: 40,
      valueXLate: 4,
    },
    "Room Cooling Unit": {
      type: "select",
      value: "",
      placeholder: "No in-room cooling unit",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = no unit, If does not comply - note unit information in Notes column",
      Appendix: "",
      information: "",
      regulatory: "",
      notes: "",
      scoreWeigh: 10,
      score: 10,
      valueXLate: 1,
    },
    "Env Alarm": {
      type: "select",
      value: "",
      placeholder: "Presence of environmental alarm",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = environmental alarm present",
      Appendix: "",
      information: "",
      regulatory: "Y",
      notes: "",
      scoreWeigh: 10,
      score: 50,
      valueXLate: 5,
    },
    "Water Sensors": {
      type: "select",
      value: "",
      placeholder: "Under floor or rack base",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = water sensors present (under floor or rack base)",
      Appendix: "",
      information: "",
      regulatory: "Y",
      notes: "",
      scoreWeigh: 10,
      score: 1000,
      valueXLate: 100,
    },
    "Water Sources": {
      type: "select",
      value: "",
      placeholder: "No faucets or capped pipes",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = no sources of water in room",
      Appendix: "",
      information: "",
      regulatory: "Y",
      notes: "",
      scoreWeigh: 0,
      score: 0,
      valueXLate: 3,
    },
    "Phone for EMS?": {
      type: "select",
      value: "",
      placeholder: "Notes",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = a phone to permit calling EMS in event of emergency, in case no cell service",
      Appendix: "",
      information: "",
      regulatory: "Y",
      notes: "",
      scoreWeigh: 0,
      score: 0,
      valueXLate: 1,
    },
    "Rack Power Std": {
      type: "select",
      value: "",
      placeholder: "Complies with standard",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = complies with published standard for power connections",
      Appendix: "",
      information: "",
      regulatory: "",
      notes: "",
      scoreWeigh: 10,
      score: 50,
      valueXLate: 5,
    },
    "Power Cord Safety": {
      type: "select",
      value: "",
      placeholder: "Check tripping hazard, alignment",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check:
        "Complies = everything looks good, Does not comply = power cords running wrongly (tripping, clothesline). Note violation in notes column",
      Appendix: "",
      information: "",
      regulatory: "",
      notes: "",
      scoreWeigh: 10,
      score: 50,
      valueXLate: 5,
    },
    "UPS Available": {
      type: "select",
      value: "",
      placeholder: "UPS or Orange outlet",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = UPS in Rack OR UPS backed circuits (Orange Outlet) is present. Note the type in the 'Notes' column",
      Appendix: "",
      information: "",
      regulatory: "",
      notes: "",
      scoreWeigh: 0,
      score: 0,
      valueXLate: 5,
    },
    "UPS Red Outlet": {
      type: "select",
      value: "",
      placeholder: "UPS connected to red outlet",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = In rack UPS unit powered by Red outlets (Generator backup)",
      Appendix: "",
      information: "",
      regulatory: "",
      notes: "",
      scoreWeigh: 0,
      score: 0,
      valueXLate: 5,
    },
    "IT UPS Covered": {
      type: "select",
      value: "",
      placeholder: "All IT devices on UPS",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = All IT devices have at least one cord connected to a UPS source",
      Appendix: "",
      information: "",
      regulatory: "",
      notes: "",
      scoreWeigh: 10,
      score: 50,
      valueXLate: 5,
    },

    "Orange Outlets": {
      type: "select",
      value: "",
      placeholder: "Presence of orange outlets",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = Orange outlets partially powered by Orange outlets (Building UPS)",
      Appendix: "",
      information: "",
      regulatory: "",
      notes: "",
      scoreWeigh: 0,
      score: 0,
      valueXLate: 3,
    },
    "Generator Backup": {
      type: "select",
      value: "",
      placeholder: "Facility generator support",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = Facility backup power present",
      Appendix: "",
      information: "",
      regulatory: "",
      notes: "",
      scoreWeigh: 0,
      score: 0,
      valueXLate: 5,
    },
    "Fire Suppression System?": {
      type: "select",
      value: "",
      placeholder: "Type of Suppression",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = Sprinkler, Halon, Other in room Note type in Notes column",
      Appendix: "",
      information: "",
      regulatory: "Y",
      notes: "",
      scoreWeigh: 0,
      score: 0,
      valueXLate: 5,
    },
    "Smoke Detectors Present?": {
      type: "select",
      value: "",
      placeholder: "Type of Suppression",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = Smoke Detectors visible in the ceiling space",
      Appendix: "",
      information: "",
      regulatory: "Y",
      notes: "",
      scoreWeigh: 0,
      score: 0,
      valueXLate: 5,
    },
    "Fire Indicators Present?": {
      type: "select",
      value: "",
      placeholder: "Notes",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = Fire indicator Device in room for occupant notification",
      Appendix: "",
      information: "",
      regulatory: "Y",
      notes: "",
      scoreWeigh: 0,
      score: 0,
      valueXLate: 5,
    },
    "Emergency Power / Lighting?": {
      type: "select",
      value: "",
      placeholder: "Notes",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = Red outlets, Emergency lighting in the room",
      Appendix: "",
      information: "",
      regulatory: "Y",
      notes: "",
      scoreWeigh: 0,
      score: 0,
      valueXLate: 5,
    },
    "Emergency Frog Lights?": {
      type: "select",
      value: "",
      placeholder: "Notes",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: 'Complies = Emergency lighting "frog lights" in room',
      Appendix: "",
      information: "",
      regulatory: "Y",
      notes: "",
      scoreWeigh: 0,
      score: 0,
      valueXLate: 3,
    },
    "Validate Conduit Penetrations": {
      type: "select",
      value: "",
      placeholder: "Notes",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = ALL conduit penetrations have voids filled with firestop",
      Appendix: "",
      information: "",
      regulatory: "Y",
      notes: "",
      scoreWeigh: 0,
      score: 0,
      valueXLate: 5,
    },
    "Validate Maintenance Penetrations": {
      type: "select",
      value: "",
      placeholder: "Notes",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = Appropriate fire rating label attached to wall",
      Appendix: "",
      information: "",
      regulatory: "Y",
      notes: "",
      scoreWeigh: 0,
      score: 0,
      valueXLate: 5,
    },
    '36" Clearance Fire / Power Panels': {
      type: "select",
      value: "",
      placeholder: "Notes",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "N/A= no Panel; Complies= Panel with clearance; Does not comply=Panel not enough clearance",
      Appendix: "",
      information: "",
      regulatory: "Y",
      notes: "",
      scoreWeigh: 0,
      score: 0,
      valueXLate: 5,
    },
    "Room State": {
      type: "select",
      value: "",
      placeholder: "Notes",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = no litter or clutter in room",
      Appendix: "",
      information: "",
      regulatory: "Y",
      notes: "",
      scoreWeigh: 0,
      score: 0,
      valueXLate: 3,
    },
    "Tripping / Clothesline Hazards": {
      type: "select",
      value: "",
      placeholder: "Notes",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = No cables, wires or objects running in an unsafe way",
      Appendix: "",
      information: "",
      regulatory: "Y",
      notes: "",
      scoreWeigh: 0,
      score: 0,
      valueXLate: 5,
    },
    "Room Used for Storage?": {
      type: "select",
      value: "",
      placeholder: "Notes",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = no boxes spares or other items stored in room",
      Appendix: "",
      information: "",
      regulatory: "Y",
      notes: "",
      scoreWeigh: 0,
      score: 0,
      valueXLate: 3,
    },
    "Trash Disposeal Loction?": {
      type: "select",
      value: "",
      placeholder: "Notes",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies = trash can in room",
      Appendix: "",
      information: "",
      regulatory: "Y",
      notes: "",
      scoreWeigh: 0,
      score: 0,
      valueXLate: 3,
    },
    "Empty Trash Car?": {
      type: "select",
      value: "",
      placeholder: "Notes",
      options: ["Complies", "Does Not Comply", "N/A"],
      required: true,
      check: "Complies= In room trash can is emptied of its contents on a schedule",
      Appendix: "",
      information: "",
      regulatory: "Y",
      notes: "",
      scoreWeigh: 0,
      score: 0,
      valueXLate: 1,
    },
  },

  //   "Fire Detection *": {
  //     type: "bool",
  //     value: "",
  //     placeholder: "Input Here",
  //     options: [],
  //     required: false,
  //     APIMatch: "",
  //   },
  //   "Fire Detection Type": {
  //     type: "select",
  //     value: "",
  //     placeholder: "Input Here",
  //     options: Survey.Fire,
  //     required: false,
  //     APIMatch: "",
  //   },
  //   "Fire Suppression *": {
  //     type: "bool",
  //     value: "",
  //     placeholder: "Input Here",
  //     options: [],
  //     required: false,
  //     APIMatch: "",
  //   },
  //   "Fire Suppression Type": {
  //     type: "select",
  //     value: "",
  //     placeholder: "Input Here",
  //     options: Survey.FireSuppression,
  //     required: false,
  //     APIMatch: "",
  //   },
  //   "Fire Walls *": {
  //     type: "bool",
  //     value: "",
  //     placeholder: "Input Here",
  //     options: [],
  //     required: false,
  //     APIMatch: "",
  //   },
  //   "Fire Wall Rating": {
  //     type: "number",
  //     value: "",
  //     placeholder: "Input Here",
  //     options: [],
  //     required: false,
  //     APIMatch: "",
  //   },
  //   "Fire Notes": {
  //     type: "textarea",
  //     value: "",
  //     placeholder: "Input Here",
  //     options: [],
  //     required: false,
  //     APIMatch: "",
  //   },
  // },
  NewAssets: CreateTemplatesAssets,
  NewRacks: CreateTemplatesRacks,
  NewPDUs: CreateTemplatesPDU,
};

const state = {
  Location: [Template.Location],
  // Rooms: [],
  Racks: [],
  PDUs: [],
  Assets: [],
  Blades: [],
  StructuredCabling: [],
  UPSs: [],
  ATSs: [],
  Panels: [],
  Receptacles: [],
  LoggedIn: false,
  Settings: {
    localStorage: true,
  },
  OpenRU: [],
  Current: {
    Naming: [],
    DataBaseUUID: "",
    DataBaseTime: "",
    MLTCreatedCount: 0,
    StructuredCablingSet: {
      rack: null,
      asset: null,
      port: null,
      rack2: null,
      asset2: null,
      port2: null,
      Chassis: null,
      Slot: null,
      "# Operation *": "ADD",
      "Object *": "STRUCTURED-CABLING",
      "Starting Item Location *": "",
      "Starting Port Index *": "",
      "Starting Item Name *": "",
      "Starting Port Name *": "",
      "Starting Port Connector *": "RJ45",
      "Ending Item Location *": "",
      "Ending Port Index *": "",
      "Ending Item Name *": "",
      "Ending Port Name *": "",
      "Ending Port Connector *": "RJ45",
      "Cable Grade *": "Cat6",
      "Media **": "Twisted Pair",
      "Length (ft/m) *": "3",
      "Length Units *": "US",
      "Color *": "Blue",
      Connected: false,
    },
    Location: 0,
    Rooms: 0,
    Racks: 0,
    PDUs: 0,
    Assets: 0,
    Blades: 0,
    StructuredCabling: 0,
    UPSs: 0,
    ATSs: 0,
    Panels: 0,
    Receptacles: 0,
    NewRacks: 0,
    NewPDUs: 0,
    NewAssets: 0,
    SurveyGlobal: 0,
    SurveyRoom: 0,
    SurveySecurity: 0,
    SurveySafety: 0,
    SurveySite: 0,
  },
  NewRacks: [],
  NewPDUs: [],
  NewAssets: [],
  NewUPSs: [],
  NewATSs: [],
  SurveyGlobal: [Template.SurveyGlobal],
  SurveySite: [Template.SurveySite],
  SurveyRoom: [Template.SurveyRoom],
  SurveySecurity: [Template.SurveySecurity],
  SurveySafety: [Template.SurveySafety],

  // Survey: {
  //   Location: [],
  //   Rooms: [],
  //   Racks: [],
  //   Assets: [],
  // },
};

export default Template;
export { state };

// let text = {
//   type: "text",
//   value: "",
//   placeholder: "Input Here",
//   options: [],
//   required: false,
//   APIMatch: "",
//   NEXT: "HOLD FOR ADDITIONAL INFO", Export: "",
// };

// let number = {
//   type: "number",
//   value: 0,
//   options: [],
//   required: false,
//   aPIMatch: "",
//   NEXT: "HOLD FOR ADDITIONAL INFO", Export: "",
// };

// let date = {
//   type: "date",
//   value: "2007-06-09",
//   options: [],
//   required: false,
//   aPIMatch: "",
//   NEXT: "HOLD FOR ADDITIONAL INFO", Export: "",
// };

// let bool = {
//   type: "bool",
//   value: false,
//   options: [],
//   required: false,
//   aPIMatch: "",
//   NEXT: "HOLD FOR ADDITIONAL INFO", Export: "",
// };

// let select = {
//   type: "select",
//   value: "",
//   options: [],
//   required: false,
//   aPIMatch: "",
//   NEXT: "HOLD FOR ADDITIONAL INFO", Export: "",
// };
