export const LocationAdditionalFields = {
  "New dcTrack Location Code": {
    type: "text",
    value: "",
    defaultValue: () => this.value,
    placeholder: "Input Here",
    options: [],
    required: false,
    APIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "Is Default Location": {
    type: "bool",
    value: false,
    defaultValue: () => this.value,
    options: [],
    required: false,
    aPIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "Location Type": {
    type: "text",
    value: "",
    defaultValue: () => this.value,
    placeholder: "Input Here",
    options: [],
    required: false,
    APIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  Units: {
    type: "text",
    value: "",
    defaultValue: () => this.value,
    placeholder: "Input Here",
    options: [],
    required: false,
    APIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "Outer Room Dim - L": {
    type: "text",
    value: "",
    defaultValue: () => this.value,
    placeholder: "Input Here",
    options: [],
    required: false,
    APIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "Outer Room Dim - W": {
    type: "text",
    value: "",
    defaultValue: () => this.value,
    placeholder: "Input Here",
    options: [],
    required: false,
    APIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "Data Center Height Raised Floor": {
    type: "text",
    value: "",
    defaultValue: () => this.value,
    placeholder: "Input Here",
    options: [],
    required: false,
    APIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "Data Center Height Finished Floor to Finished Ceiling": {
    type: "text",
    value: "",
    defaultValue: () => this.value,
    placeholder: "Input Here",
    options: [],
    required: false,
    APIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "Data Center Height Finished Ceiling to Slab Ceiling": {
    type: "text",
    value: "",
    defaultValue: () => this.value,
    placeholder: "Input Here",
    options: [],
    required: false,
    APIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  Street: {
    type: "text",
    value: "",
    defaultValue: () => this.value,
    placeholder: "Input Here",
    options: [],
    required: false,
    APIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "Street (Line 2)": {
    type: "text",
    value: "",
    defaultValue: () => this.value,
    placeholder: "Input Here",
    options: [],
    required: false,
    APIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  City: {
    type: "text",
    value: "",
    defaultValue: () => this.value,
    placeholder: "Input Here",
    options: [],
    required: false,
    APIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  State: {
    type: "text",
    value: "",
    defaultValue: () => this.value,
    placeholder: "Input Here",
    options: [],
    required: false,
    APIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "Postal Code": {
    type: "text",
    value: "",
    defaultValue: () => this.value,
    placeholder: "Input Here",
    options: [],
    required: false,
    APIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "Drawing North": {
    type: "text",
    value: "",
    defaultValue: () => this.value,
    placeholder: "Input Here",
    options: [],
    required: false,
    APIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "Grid Label": {
    type: "text",
    value: "",
    defaultValue: () => this.value,
    placeholder: "Input Here",
    options: [],
    required: false,
    APIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "Vertical Row Orientation": {
    type: "text",
    value: "",
    defaultValue: () => this.value,
    placeholder: "Input Here",
    options: [],
    required: false,
    APIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "Horizontal Row Orientation": {
    type: "text",
    value: "",
    defaultValue: () => this.value,
    placeholder: "Input Here",
    options: [],
    required: false,
    APIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "Location Picture Path": {
    type: "text",
    value: "",
    defaultValue: () => this.value,
    placeholder: "Input Here",
    options: [],
    required: false,
    APIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "Enable Virtual Power Chain": {
    type: "bool",
    value: false,
    defaultValue: () => this.value,
    options: [],
    required: false,
    aPIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "Power IQ Appliance": {
    type: "text",
    value: "",
    defaultValue: () => this.value,
    placeholder: "Input Here",
    options: [],
    required: false,
    APIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "Power IQ Object Type": {
    type: "text",
    value: "",
    defaultValue: () => this.value,
    placeholder: "Input Here",
    options: [],
    required: false,
    APIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "Power IQ Object ID": {
    type: "text",
    value: "",
    defaultValue: () => this.value,
    placeholder: "Input Here",
    options: [],
    required: false,
    APIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "Power IQ Object Name": {
    type: "text",
    value: "",
    defaultValue: () => this.value,
    placeholder: "Input Here",
    options: [],
    required: false,
    APIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
  "Capacity(kW)": {
    type: "text",
    value: "",
    defaultValue: () => this.value,
    placeholder: "Input Here",
    options: [],
    required: false,
    APIMatch: "",
    NEXT: "HOLD FOR ADDITIONAL INFO",
  },
};
